### ISSUE TITLE
电子书

### ISSUE THREAD

**Issue by fyhhub** [Liugq5713/nav#2]
underscore源码分析
https://yoyoyohamapi.gitbooks.io/undersercore-analysis/content/

深入浅出 Webpack
http://webpack.wuhaolin.cn/

 React小书
http://huziketang.mangojuice.top/books/react/

深入理解 TypeScript
https://jkchao.github.io/typescript-book-chinese/

前端面试图谱
https://yuchengkai.cn/docs/frontend/

JavaScript Promise迷你书（中文版）
http://liubin.org/promises-book/

**Comment by Liugq5713** [comment]
thx
